### ISSUE TITLE
Where to put conf.cfg?

### ISSUE THREAD

**Issue by koenvervloesem** [treussart/domoticz_skill#9]
Where exactly should I put this file conf.cfg? I installed the Domoticz skill with the Mycroft command 'install domoticz skill', I put a conf.cfg file with the right parameters for my Domoticz setup in ~/.mycroft/skills/DomoticzSkill/conf.cfg and I restarted Mycroft, but it doesn't seem to pick up the config.

**Comment by treussart** [comment]
Hi, it's the right place for conf.cfg.  Maybe it will be useful if I add a test for the connection with Domoticz ?

**Comment by koenvervloesem** [comment]
That would be useful, yes!

**Comment by treussart** [comment]
I added a script for test your connection with Domoticz:
Launch :
`python domoticz_skill/test_connection_domoticz.py`

**Comment by koenvervloesem** [comment]
It gives this error message:

```
koan@x1:/opt/mycroft/skills/domoticz_skill$ workon mycroft
(mycroft) koan@x1:/opt/mycroft/skills/domoticz_skill$ python test_connection_domoticz.py 
  File "test_connection_domoticz.py", line 16
    password = .config.get('domoticz', 'password')
               ^
SyntaxError: invalid syntax
```

When I remove the dot, which seems wrong to me, I get another error message:

```
(mycroft) koan@x1:/opt/mycroft/skills/domoticz_skill$ python test_connection_domoticz.py 
  File "test_connection_domoticz.py", line 24
    if f.getcode() == 200:
                         ^
SyntaxError: invalid syntax
```

**Comment by treussart** [comment]
Ok retest, I corrected the bugs !! sorry

**Comment by koenvervloesem** [comment]
Ok the test works now and says the connection is OK, when I put my config file in the same directory as the skill.

But Mycroft still doesn't seem to recognize any of my devices on Domoticz. For instance, I have this in my conf.cfg:

```
[devices]
Temperature-refrigerator = 36
Temperature-outside = 115
Temperature-freezer = 43
Tempetrature-hall = 123
Desktop = 42
```

And things like "Turn on the desktop", "What's the temperature of the refrigerator?" and so on aren't recognized. For the temperatures, Mycroft answers the temperature from the weather skill, and for the other devices I get "Sorry, I didn't catch that. Please rephrase your request."

**Comment by treussart** [comment]
Desktop is a switch in Domoticz ?
If you disable the weather skill, it works ?

**Comment by koenvervloesem** [comment]
Yes, Desktop is a switch to turn on and off my computer.

How do I disable other skills? I can't find it in Mycroft's documentation.

**Comment by treussart** [comment]
Desktop was not in the list of keywords, I added.

Simply remove the folder of the skills and reload Mycroft.

**Comment by koenvervloesem** [comment]
Thanks! But that's weird, when I remove the folder of the weather skill and reload Mycroft, the folder comes back! Even when I have "update: false" in the server configuration.
I see all the keywords of the Domoticz skill being registered in the Mycroft debug output, but still none of my commands are recognized... I'll have to take a closer look later when I have more time.

**Comment by mraeymaekers** [comment]
Hi, Thanks for your work on this skill! I tried to install it today on my raspbian installation of MyCroft (NOT picroft).

I followed below steps:

cd /opt/mycroft/skills
sudo git clone https://github.com/treussart/domoticz_skill

Then I altered the conf.cfg file in /opt/mycroft/skills/domoticz_skill   
to add right IP of domoticz server and added a light point

When restarting mycroft, I get following error:


21:51:20.547 - mycroft.skills.core:load_skill:106 - INFO - ATTEMPTING TO LOAD SKILL: domoticz_skill with ID domoticz_skill
21:51:20.564 - mycroft.skills.core:load_skill:145 - ERROR - Failed to load skill: domoticz_skill
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 116, in load_skill
('.py', 'rb', imp.PY_SOURCE)
File "/usr/lib/python3.5/imp.py", line 234, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.5/imp.py", line 172, in load_source
module = _load(spec)
File "<frozen importlib._bootstrap>", line 693, in _load
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 673, in exec_module
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "/opt/mycroft/skills/domoticz_skill/__init__.py", line 27, in <module>
Domoticz = __import__('Domoticz').Domoticz
File "/opt/mycroft/skills/domoticz_skill/Domoticz.py", line 3, in <module>
import ConfigParser
ImportError: No module named 'ConfigParser'

Many thanks in advance for your assistance.
